<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20200319135847_DatabaseInitialization.cs" />
    <Compile Remove="Migrations\20200319135847_DatabaseInitialization.Designer.cs" />
    <Compile Remove="Migrations\20200319142221_DatabaseInitialization.cs" />
    <Compile Remove="Migrations\20200319142221_DatabaseInitialization.Designer.cs" />
    <Compile Remove="Migrations\20200319142516_DatabaseInitialization.cs" />
    <Compile Remove="Migrations\20200319142516_DatabaseInitialization.Designer.cs" />
    <Compile Remove="Migrations\20200319142606_DatabaseInitialization.cs" />
    <Compile Remove="Migrations\20200319142606_DatabaseInitialization.Designer.cs" />
    <Compile Remove="Migrations\20200320131409_update.cs" />
    <Compile Remove="Migrations\20200320131409_update.Designer.cs" />
    <Compile Remove="Migrations\20200320144025_InicializacaodoBandoDeDados.cs" />
    <Compile Remove="Migrations\20200320144025_InicializacaodoBandoDeDados.Designer.cs" />
    <Compile Remove="Migrations\20200320144229_update.cs" />
    <Compile Remove="Migrations\20200320144229_update.Designer.cs" />
    <Compile Remove="Migrations\20200320144256_update.cs" />
    <Compile Remove="Migrations\20200320144256_update.Designer.cs" />
    <Compile Remove="Migrations\20200322134912_Update1.cs" />
    <Compile Remove="Migrations\20200322134912_Update1.Designer.cs" />
    <Compile Remove="Migrations\20200322135115_Update2.cs" />
    <Compile Remove="Migrations\20200322135115_Update2.Designer.cs" />
    <Compile Remove="Migrations\20200322161459_InicializacaodoBandoDeDados.cs" />
    <Compile Remove="Migrations\20200322161459_InicializacaodoBandoDeDados.Designer.cs" />
    <Compile Remove="Migrations\20200323145059_bla.cs" />
    <Compile Remove="Migrations\20200323145059_bla.Designer.cs" />
    <Compile Remove="Migrations\20200325001049_index.cs" />
    <Compile Remove="Migrations\20200325001049_index.Designer.cs" />
    <Compile Remove="Migrations\20200325123402_InicializacaodoBandoDeDados.cs" />
    <Compile Remove="Migrations\20200325123402_InicializacaodoBandoDeDados.Designer.cs" />
    <Compile Remove="Migrations\20200411143307_CriandoTabelaDeSetores.cs" />
    <Compile Remove="Migrations\20200411143307_CriandoTabelaDeSetores.Designer.cs" />
    <Compile Remove="Migrations\20200411143717_CriandoTabelaDeSetores.cs" />
    <Compile Remove="Migrations\20200411143717_CriandoTabelaDeSetores.Designer.cs" />
    <Compile Remove="Migrations\20200411144503_AdicionandoSetorNaTabelaDeAtivo.cs" />
    <Compile Remove="Migrations\20200411144503_AdicionandoSetorNaTabelaDeAtivo.Designer.cs" />
    <Compile Remove="Migrations\20200411144921_CriandoTabelaDeAcompanhamento.cs" />
    <Compile Remove="Migrations\20200411144921_CriandoTabelaDeAcompanhamento.Designer.cs" />
    <Compile Remove="Migrations\20200414122244_blala.cs" />
    <Compile Remove="Migrations\20200414122244_blala.Designer.cs" />
    <Compile Remove="Migrations\20200414130514_InicializacaodoBandoDeDados.cs" />
    <Compile Remove="Migrations\20200414130514_InicializacaodoBandoDeDados.Designer.cs" />
    <Compile Remove="Migrations\20200626123303_AdicionandoCampoTipoDeInvestimento.cs" />
    <Compile Remove="Migrations\20200626123303_AdicionandoCampoTipoDeInvestimento.Designer.cs" />
    <Compile Remove="Migrations\20200626123801_AdicionandoCampoTipoDeInvestimento.cs" />
    <Compile Remove="Migrations\20200626123801_AdicionandoCampoTipoDeInvestimento.Designer.cs" />
    <Compile Remove="Migrations\20200708125949_AdicionandoColunaTipoDeOperacao.cs" />
    <Compile Remove="Migrations\20200708125949_AdicionandoColunaTipoDeOperacao.Designer.cs" />
    <Compile Remove="Migrations\20200708130221_AdicionandoColunaTipoDeOperacao.cs" />
    <Compile Remove="Migrations\20200708130221_AdicionandoColunaTipoDeOperacao.Designer.cs" />
    <Compile Remove="Migrations\20200708143202_AdicionandoNovaColunaTipoDeOperacao.cs" />
    <Compile Remove="Migrations\20200708143202_AdicionandoNovaColunaTipoDeOperacao.Designer.cs" />
    <Compile Remove="Migrations\20230717203711_InicializacaodoBandoDeDados.cs" />
    <Compile Remove="Migrations\20230717203711_InicializacaodoBandoDeDados.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.0" />
  </ItemGroup>


</Project>
