// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using alderam.stocks.api.Database;

namespace alderam.stocks.api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200319142606_DatabaseInitialization")]
    partial class DatabaseInitialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("alderam.stocks.api.Models.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Ativo");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Operacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<double>("Corretagem")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDaOperacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("Emolumentos")
                        .HasColumnType("float");

                    b.Property<double>("ISS")
                        .HasColumnType("float");

                    b.Property<double>("PrecoDeCompra")
                        .HasColumnType("float");

                    b.Property<int>("Quantitidade")
                        .HasColumnType("int");

                    b.Property<double>("TaxaDeLiquidacao")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Operacao", b =>
                {
                    b.HasOne("alderam.stocks.api.Models.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
