// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using alderam.stocks.api.Database;

namespace alderam.stocks.api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200708143304_AdicionandoNovaColunaTipoDeOperacao")]
    partial class AdicionandoNovaColunaTipoDeOperacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("alderam.stocks.api.Models.Acompanhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoDeCompra")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("Acompanhamentos");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("DataDaUltimaCotacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal?>("PrecoAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubsetorId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoDeInvestimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SubsetorId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Boleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Corretagem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataDaOperacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Emolumentos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("OperacaoEmLeilao")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaxaDaCoretagem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxaDeLiquidacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDaCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDaOperacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Boletas");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Operacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<int>("BoletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDaOperacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecoDeCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantitidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeOperacao")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<decimal>("ValorDaOperacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("BoletaId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Subsetor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Subsetores");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Acompanhamento", b =>
                {
                    b.HasOne("alderam.stocks.api.Models.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Ativo", b =>
                {
                    b.HasOne("alderam.stocks.api.Models.Subsetor", "Subsetor")
                        .WithMany()
                        .HasForeignKey("SubsetorId");
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Operacao", b =>
                {
                    b.HasOne("alderam.stocks.api.Models.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alderam.stocks.api.Models.Boleta", "Boleta")
                        .WithMany("Operacoes")
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("alderam.stocks.api.Models.Subsetor", b =>
                {
                    b.HasOne("alderam.stocks.api.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
